"""initial schema

Revision ID: a35726cabdd3
Revises: 
Create Date: 2026-04-01 11:09:07.624253

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a35726cabdd3'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('api_cache')
    with op.batch_alter_table('clicks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=True))
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               nullable=False,
               autoincrement=True)
        batch_op.alter_column('hotel_id',
               existing_type=sa.TEXT(),
               type_=sa.String(length=100),
               existing_nullable=False)
        batch_op.alter_column('hotel_name',
               existing_type=sa.TEXT(),
               type_=sa.String(length=200),
               existing_nullable=True)
        batch_op.alter_column('provider',
               existing_type=sa.TEXT(),
               type_=sa.String(length=50),
               existing_nullable=False)
        batch_op.alter_column('target_url',
               existing_type=sa.TEXT(),
               type_=sa.String(length=2000),
               existing_nullable=False)
        batch_op.alter_column('source_page',
               existing_type=sa.TEXT(),
               type_=sa.String(length=500),
               existing_nullable=True)
        batch_op.alter_column('user_ip',
               existing_type=sa.TEXT(),
               type_=sa.String(length=45),
               existing_nullable=True)
        batch_op.alter_column('user_agent',
               existing_type=sa.TEXT(),
               type_=sa.String(length=500),
               existing_nullable=True)
        batch_op.alter_column('created_at',
               existing_type=sa.TIMESTAMP(),
               type_=sa.DateTime(),
               existing_nullable=True,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
        batch_op.create_index(batch_op.f('ix_clicks_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_clicks_hotel_id'), ['hotel_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_clicks_user_id'), ['user_id'], unique=False)
        batch_op.create_foreign_key('fk_clicks_user_id_users', 'users', ['user_id'], ['id'], ondelete='SET NULL')

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('membership_tier', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('membership_expires_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('search_count_today', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('last_search_date', sa.Date(), nullable=True))
        batch_op.create_index(batch_op.f('ix_users_membership_tier'), ['membership_tier'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_membership_tier'))
        batch_op.drop_column('last_search_date')
        batch_op.drop_column('search_count_today')
        batch_op.drop_column('membership_expires_at')
        batch_op.drop_column('membership_tier')

    with op.batch_alter_table('clicks', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_clicks_user_id'))
        batch_op.drop_index(batch_op.f('ix_clicks_hotel_id'))
        batch_op.drop_index(batch_op.f('ix_clicks_created_at'))
        batch_op.alter_column('created_at',
               existing_type=sa.DateTime(),
               type_=sa.TIMESTAMP(),
               existing_nullable=True,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
        batch_op.alter_column('user_agent',
               existing_type=sa.String(length=500),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('user_ip',
               existing_type=sa.String(length=45),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('source_page',
               existing_type=sa.String(length=500),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('target_url',
               existing_type=sa.String(length=2000),
               type_=sa.TEXT(),
               existing_nullable=False)
        batch_op.alter_column('provider',
               existing_type=sa.String(length=50),
               type_=sa.TEXT(),
               existing_nullable=False)
        batch_op.alter_column('hotel_name',
               existing_type=sa.String(length=200),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('hotel_id',
               existing_type=sa.String(length=100),
               type_=sa.TEXT(),
               existing_nullable=False)
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=True)
        batch_op.drop_column('user_id')

    op.create_table('api_cache',
    sa.Column('id', sa.INTEGER(), nullable=True),
    sa.Column('cache_key', sa.TEXT(), nullable=False),
    sa.Column('response', sa.TEXT(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('expires_at', sa.TIMESTAMP(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cache_key')
    )
    # ### end Alembic commands ###
